### ISSUE TITLE
Simplify gitpod init

### ISSUE THREAD

**Issue by Mizux** [Shadouw/CPPToyProblems#2]
why not using

```yml
tasks:
  - init: cmake -S. -Bbuild -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
```

note: gitpod seems to have cmake 3.17 installed and since cmake 3.11 IIRC you can use the official `-S` option (ed you still have the hidden `-H` command otherwise...)

**Comment by Shadouw** [comment]
Thanks for the hint. My OS (Kubuntun 18.04) comes with cmake 3.10 and I like to support it.

To be honest, I haven't used gitpod for a while since I never found out how to run and debug a C++ program.

**Comment by Mizux** [comment]
once the gitpod is started you can simply type:
`cmake --build build --target all` to build everything
then
`cmake --build build --target test` to run test (if you use CTest).

for debug simply add a `-DCMAKE_BUILD_TYPE=Debug` as usual  ;)
ref: https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html

note: I'm also testing gitpod currently
see: https://github.com/Mizux/cmake-cpp

**Comment by Shadouw** [comment]
Do you have some more information like using breakbpoints and debugging into the code? Compiling and running from command line is fine but therefore no ide is needed.
A while ago I've created a Gitpod thread: https://spectrum.chat/gitpod/general/gitpod-and-c~f6f89cb1-be05-48ab-856b-1c75fba369e3
We only managed to get clang-tidy linter running

**Comment by Shadouw** [comment]
Sorry, I had an error in reasoning. The gitpod.yml for sure doesn't affect my local build system. I've simplified the init task as suggested.
